### ISSUE TITLE
My Product KPI dashboard breaks with 404 errors during navigation and is unrecoverable

### ISSUE THREAD

**Issue by magorlick** [rilldata/rill-developer#1060]
I can't give you repro steps but I see this all the time across my projects.  Might be related to trying to edit the config or navigating from models to sources.

This is the error I see in the terminal:

TypeError: Cannot read properties of undefined (reading 'id')
    at MetricsViewActions.getMetricsViewMeta (/Users/marissagorlick/Documents/rilldata/rill-developer-kpi/web-local/src/common/rill-developer-service/MetricsViewActions.ts:108:42)
    at RillDeveloperService.dispatch (/Users/marissagorlick/Documents/rilldata/rill-developer-kpi/web-local/src/common/rill-developer-service/RillDeveloperService.ts:89:54)
    at /Users/marissagorlick/Documents/rilldata/rill-developer-kpi/web-local/src/server/controllers/MetricsViewController.ts:29:33
    at Function.wrapAction (/Users/marissagorlick/Documents/rilldata/rill-developer-kpi/web-local/src/server/controllers/EntityController.ts:99:30)
    at MetricsViewController.handleGetMetricsMeta (/Users/marissagorlick/Documents/rilldata/rill-developer-kpi/web-local/src/server/controllers/MetricsViewController.ts:28:28)
    at /Users/marissagorlick/Documents/rilldata/rill-developer-kpi/web-local/src/server/controllers/MetricsViewController.ts:12:12
    at Layer.handle [as handle_request] (/Users/marissagorlick/Documents/rilldata/rill-developer-kpi/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/marissagorlick/Documents/rilldata/rill-developer-kpi/node_modules/express/lib/router/route.js:144:13)
    at Route.dispatch (/Users/marissagorlick/Documents/rilldata/rill-developer-kpi/node_modules/express/lib/router/route.js:114:3)
    at Layer.handle [as handle_request] (/Users/marissagorlick/Documents/rilldata/rill-developer-kpi/node_modules/express/lib/router/layer.js:95:5)

**Comment by magorlick** [comment]
A video of me encountering this problem with our `init-example` project, it might even be 2 issues. Notice how the model is on the wrong port when I try to open the asset and there is no data until I make a small change and it looks for the source again (?).  Clicking the dashboard button on a valid example led to a 404 dashboard error.

https://user-images.githubusercontent.com/5587788/197265649-260ff93a-e13d-4c98-9952-37cec09fc6fd.mp4

**Comment by magorlick** [comment]
The error in my terminal:
```
Error: Catalog Error: Table with name e_shop_model does not exist!
Did you mean "e_shop_clothing"?
LINE 7:       e_shop_model
              ^
    at DuckDBClient.request (/Users/marissagorlick/Documents/rilldata/rill-developer/web-local/src/common/database-service/DuckDBClient.ts:169:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at DuckDBClient.execute (/Users/marissagorlick/Documents/rilldata/rill-developer/web-local/src/common/database-service/DuckDBClient.ts:55:20)
    at DatabaseTimeSeriesActions.estimateIdealRollupInterval (/Users/marissagorlick/Documents/rilldata/rill-developer/web-local/src/common/database-service/DatabaseTimeSeriesActions.ts:362:25)
    at DatabaseService.dispatch (/Users/marissagorlick/Documents/rilldata/rill-developer/web-local/src/common/database-service/DatabaseService.ts:78:12)
    at ActionQueueOrchestrator.run (/Users/marissagorlick/Documents/rilldata/rill-developer/web-local/src/common/priority-action-queue/ActionQueueOrchestrator.ts:30:24)
```

**Comment by hamilton** [comment]
I think this one should have been fixed w/ the new remote sources branch. @magorlick can you confirm?

**Comment by magorlick** [comment]
Yes, this is fixed now.
