### ISSUE TITLE
we should be handling technically-invalid dates in DuckDB in dashboards

### ISSUE THREAD

**Issue by hamilton** [rilldata/rill-developer#1065]
Invalid dates in duckdb cause dashboard crashing issues. In the below dataset, we have a day of 0, which means we get an error when using `make_date` with the `Day` column.

steps to reproduce:

### create a new dashboard out of this model
```
select *, make_date(Year, Month, Day) as dt from city_temperature
```

### observe the errror
I receive the following error:
```
Error: Conversion Error: Date out of range: 2012-3-0
    at DuckDBClient.request (/Users/hamiltonulmer/Code/rill/rill-developer/web-local/src/common/database-service/DuckDBClient.ts:175:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at DuckDBClient.execute (/Users/hamiltonulmer/Code/rill/rill-developer/web-local/src/common/database-service/DuckDBClient.ts:55:20)
    at DatabaseTimeSeriesActions.estimateIdealRollupInterval (/Users/hamiltonulmer/Code/rill/rill-developer/web-local/src/common/database-service/DatabaseTimeSeriesActions.ts:362:25)
    at DatabaseService.dispatch (/Users/hamiltonulmer/Code/rill/rill-developer/web-local/src/common/database-service/DatabaseService.ts:78:12)
    at ActionQueueOrchestrator.run (/Users/hamiltonulmer/Code/rill/rill-developer/web-local/src/common/priority-action-queue/ActionQueueOrchestrator.ts:30:24)
```

**Comment by magorlick** [comment]
When I run `MAKE_DATE(year, month,day)` on the example data set e_shop_clothing (init-example to download) I get a different error.

**Browser Inspector Console:**
`start-51c27cc1.js:1          GET http://localhost:8080/api/v1/metrics-views/8fb5f66f-a8af-e3c9-1915-5cdd0a58050d/meta 500 (Internal Server Error)`


**Terminal** 
```
TypeError: Cannot read properties of undefined (reading 'setSocketServer')
  at new ExpressServer (/Users/marissagorlick/Documents/rilldata/rill-developer/web-local/src/server/ExpressServer.ts:51:25)
  at StartCommand.sendActions (/Users/marissagorlick/Documents/rilldata/rill-developer/web-local/src/cli/StartCommand.ts:27:12)
  at StartCommand.run (/Users/marissagorlick/Documents/rilldata/rill-developer/web-local/src/cli/DataModelerCliCommand.ts:107:16)
  at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by hamilton** [comment]
This is a duplicate of #1570
