### ISSUE TITLE
Using ts as column in source model causes issues with timeseries query.

### ISSUE THREAD

**Issue by hamilton** [rilldata/rill-developer#1205]
(this is a blocker for `0.14`)

We appear to have a race condition that may be similar to what was fixed in #1189 when running `rill init-example`.

Steps to reproduce: 
- get the binary for `0.14`
- source: `iot_telemetry_data`
- model: `select to_timestamp(ts::BIGINT) as ts, humidity, device from iot_telemetry_data`
- dashboard: autogenerated

This will generate the following grpc error for the dashboard:

```
Error: grpc: received message larger than max (26683905 vs. 4194304)
    at DuckDBClient.request (/snapshot/rill-developer/web-local/dist/web-local/src/common/database-service/DuckDBClient.js:138:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async DuckDBClient.execute (/snapshot/rill-developer/web-local/dist/web-local/src/common/database-service/DuckDBClient.js:45:26)
    at async DatabaseTimeSeriesActions.generateTimeSeries (/snapshot/rill-developer/web-local/dist/web-local/src/common/database-service/DatabaseTimeSeriesActions.js:141:25)
    at async DatabaseService.dispatch (/snapshot/rill-developer/web-local/dist/web-local/src/common/database-service/DatabaseService.js:42:16)
    at async ActionQueueOrchestrator.run (/snapshot/rill-developer/web-local/dist/web-local/src/common/priority-action-queue/ActionQueueOrchestrator.js:19:32)
```

Additionally, it appears that we have another `undefined` runtime-related error seen with each model that was created through `rill init-example`:

```
request to http://localhost:8081/v1/instances/undefined/query/direct failed, reason: connect ECONNREFUSED 127.0.0.1:8081
```

![image](https://user-images.githubusercontent.com/95735/200665545-8bd7f298-994e-4062-9443-2b3269ad1baf.png)

And I get a similar lack of profiles in the source that we had that led to #1189 :

![image](https://user-images.githubusercontent.com/95735/200669793-9025e355-be1e-42ec-9709-b41d7499854c.png)

I was not able to reproduce this with using `npm run build` then `npm run cli -- init-example`, but this problem applies specifically to use the `0.14` binary generated for the release.

If this is primarily a `grpc` error, it would be good to figure out how and why we're receiving this. To date we have never encountered an issue where 27mb of data should ever be transferred over the wire in this direction. If the additional issues around the `undefined` runtime in the API call is related, that's great. If not, it'd be good to file a separate issue and tackle that.

**Comment by AdityaHegde** [comment]
The issue with `init-example` is not reproducible tried a few times on both M1 and x86 macs. Perhaps the grpc error put the app in a bad state.

The grpc error is because the timeseries query ends up returning the entire table because of a clash in column names used. `ts` being present in the source model clases with `ts` used internally in the query.
