### ISSUE TITLE
`iot_model` dashboard – switching from metrics back to dashboard creates an error

### ISSUE THREAD

**Issue by hamilton** [rilldata/rill-developer#1208]
This is kind of an odd bug since it's not exactly easy to reproduce, but I have steps:

- run `rill init-example` in a new directory
- make a dashboard for the IOT example
- go to metrics page
- switch from metrics to dashboard
- click on a filter

https://user-images.githubusercontent.com/95735/200750199-5319d865-b8a8-43c1-af94-79bd592666ed.mp4

I get the following error in the console:

```
Error: Parser Error: syntax error at or near "AND"
LINE 3:       WHERE  AND "event_datetime" >= TIMESTAMP '2020-07-12T00:01:34.000Z' AND "event_datetime" <= TIMESTAMP '2020-07-20T00:03:37.000Z'
      GROUP BY "light"
      ORDER BY measure_0 desc NULLS LAST
      LIMIT 250
    ...
                     ^
    at DuckDBClient.request (/Users/hamiltonulmer/Code/rill/rill-developer/web-local/src/common/database-service/DuckDBClient.ts:175:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at DuckDBClient.execute (/Users/hamiltonulmer/Code/rill/rill-developer/web-local/src/common/database-service/DuckDBClient.ts:55:20)
    at DatabaseService.dispatch (/Users/hamiltonulmer/Code/rill/rill-developer/web-local/src/common/database-service/DatabaseService.ts:78:12)
    at ActionQueueOrchestrator.run (/Users/hamiltonulmer/Code/rill/rill-developer/web-local/src/common/priority-action-queue/ActionQueueOrchestrator.ts:30:24)

```

**Comment by hamilton** [comment]
Began debugging but didn't quite get far enough. The culprit appears to be how we're handling `WHERE` clause templating here: https://github.com/rilldata/rill-developer/blob/main/web-local/src/common/database-service/utils.ts
