### ISSUE TITLE
Runtime crashes on migration of rill.catalog table in DuckDB

### ISSUE THREAD

**Issue by djbarnwal** [rilldata/rill-developer#1224]
After an install using `npm install` on the existing application, the following error popped up - 

```
Exception in WAL playback: Catalog Error: Cannot alter entry "catalog" because there are entries that depend on it.

{"level":"error","ts":1668416298.306085,"caller":"logging/interceptors.go:35","msg":"finished call","protocol":"grpc","grpc.component":"server","grpc.service":"rill.runtime.v1.RuntimeService","grpc.method":"ListCatalogObjects","grpc.method_type":"unary","peer.address":"127.0.0.1:61367","grpc.start_time":"2022-11-14T14:28:18+05:30","grpc.code":"Unknown","grpc.error":"panic caught: sql: Scan error on column index 4, name \"managed\": sql/driver: couldn't convert <nil> (<nil>) into type bool\n\ngoroutine 11 [running]:\ngithub.com/grpc-ecosystem/go-grpc-middleware/v2/interceptors/recovery.recoverFrom({0x104c24e40?, 0x140004d5470?}, {0x104a882e0?, 0x14000178460?}, 0x0?)\n\tgithub.com/grpc-ecosystem/go-grpc-middleware/v2@v2.0.0-rc.2.0.20220505152843-58a406687f2d/interceptors/recovery/interceptors.go:57 +0x5c\ngithub.com/grpc-ecosystem/go-grpc-middleware/v2/interceptors/recovery.UnaryServerInterceptor.func1.1()\n\tgithub.com/grpc-ecosystem/go-grpc-middleware/v2@v2.0.0-rc.2.0.20220505152843-58a406687f2d/interceptors/recovery/interceptors.go:30 +0x64\npanic({0x104a882e0, 0x14000178460})\n\truntime/panic.go:884 +0x204\ngithub.com/rilldata/rill/runtime/drivers/duckdb.(*connection).findObjects(0x1400003d380, {0x104c24e40, 0x140004d5470}, {0x104429567?, 0x140004d5470?}, {0x140008f32f8, 0x1, 0x1})\n\tgithub.com/rilldata/rill/runtime/drivers/duckdb/catalog.go:48 +0x330\ngithub.com/rilldata/rill/runtime/drivers/duckdb.(*connection).FindObjects(0x14000010108?, {0x104c24e40, 0x140004d5470}, {0x1400011c3c0?, 0x24?}, {0x1044209b2?, 0x0?})\n\tgithub.com/rilldata/rill/runtime/drivers/duckdb/catalog.go:18 +0xa0\ngithub.com/rilldata/rill/runtime/server.(*Server).ListCatalogObjects(0x140006ce2c0, {0x104c24e40, 0x140004d5470}, 0x140004dcd80)\n\tgithub.com/rilldata/rill/runtime/server/catalog.go:33 +0x11c\ngithub.com/rilldata/rill/runtime/api._RuntimeService_ListCatalogObjects_Handler.func1({0x104c24e40, 0x140004d5470}, {0x104b3f340?, 0x140004dcd80})\n\tgithub.com/rilldata/rill/runtime/api/runtime_grpc.pb.go:756 +0x74\ngithub.com/grpc-ecosystem/go-grpc-middleware/v2/interceptors/recovery.UnaryServerInterceptor.func1({0x104c24e40?, 0x140004d5470?}, {0x104b3f340?, 0x140004dcd80?}, 0x104468549?, 0x12?)\n\tgithub.com/grpc-ecosystem/go-grpc-middleware/v2@v2.0.0-rc.2.0.20220505152843-58a406687f2d/interceptors/recovery/interceptors.go:34 +0x88\ngoogle.golang.org/grpc.chainUnaryInterceptors.func1.1({0x104c24e40?, 0x140004d5470?}, {0x104b3f340?, 0x140004dcd80?})\n\tgoogle.golang.org/grpc@v1.49.0/server.go:1135 +0x60\ngithub.com/grpc-ecosystem/go-grpc-middleware/v2/interceptors.UnaryServerInterceptor.func1({0x104c24e40, 0x140004d50e0}, {0x104b3f340, 0x140004dcd80}, 0x68a3e7c7?, 0x140004dcdc0)\n\tgithub.com/grpc-ecosystem/go-grpc-middleware/v2@v2.0.0-rc.2.0.20220505152843-58a406687f2d/interceptors/server.go:22 +0x19c\ngoogle.golang.org/grpc.chainUnaryInterceptors.func1.1({0x104c24e40?, 0x140004d50e0?}, {0x104b3f340?, 0x140004dcd80?})\n\tgoogle.golang.org/grpc@v1.49.0/server.go:1138 +0x8c\ngithub.com/grpc-ecosystem/go-grpc-middleware/v2/interceptors.UnaryServerInterceptor.func1({0x104c24e40, 0x140004d50e0}, {0x104b3f340, 0x140004dcd80}, 0x140004dcd80?, 0x140004dcdc0)\n\tgithub.com/grpc-ecosystem/go-grpc-middleware/v2@v2.0.0-rc.2.0.20220505152843-58a406687f2d/interceptors/server.go:22 +0x19c\ngoogle.golang.org/grpc.chainUnaryInterceptors.func1.1({0x104c24e40?, 0x140004d50e0?}, {0x104b3f340?, 0x140004dcd80?})\n\tgoogle.golang.org/grpc@v1.49.0/server.go:1138 +0x8c\ngithub.com/grpc-ecosystem/go-grpc-middleware/v2/interceptors.UnaryServerInterceptor.func1({0x104c24e40, 0x140004d5020}, {0x104b3f340, 0x140004dcd80}, 0x10655c101?, 0x140004dcdc0)\n\tgithub.com/grpc-ecosystem/go-grpc-middleware/v2@v2.0.0-rc.2.0.20220505152843-58a406687f2d/interceptors/server.go:22 +0x19c\ngoogle.golang.org/grpc.chainUnaryInterceptors.func1.1({0x104c24e40?, 0x140004d5020?}, {0x104b3f340?, 0x140004dcd80?})\n\tgoogle.golang.org/grpc@v1.49.0/server.go:1138 +0x8c\ngoogle.golang.org/grpc.chainUnaryInterceptors.func1({0x104c24e40, 0x140004d5020}, {0x104b3f340, 0x140004dcd80}, 0x140001782a0, 0x140004de3c0)\n\tgoogle.golang.org/grpc@v1.49.0/server.go:1140 +0x120\ngithub.com/rilldata/rill/runtime/api._RuntimeService_ListCatalogObjects_Handler({0x104bf0580?, 0x140006ce2c0}, {0x104c24e40, 0x140004d5020}, 0x14000376850, 0x140008ac7a0)\n\tgithub.com/rilldata/rill/runtime/api/runtime_grpc.pb.go:758 +0x138\ngoogle.golang.org/grpc.(*Server).processUnaryRPC(0x14000378000, {0x104c29f20, 0x14000103040}, 0x140008e4240, 0x140004d4060, 0x105518940, 0x0)\n\tgoogle.golang.org/grpc@v1.49.0/server.go:1301 +0x9c4\ngoogle.golang.org/grpc.(*Server).handleStream(0x14000378000, {0x104c29f20, 0x14000103040}, 0x140008e4240, 0x0)\n\tgoogle.golang.org/grpc@v1.49.0/server.go:1642 +0x82c\ngoogle.golang.org/grpc.(*Server).serveStreams.func1.2()\n\tgoogle.golang.org/grpc@v1.49.0/server.go:938 +0x84\ncreated by google.golang.org/grpc.(*Server).serveStreams.func1\n\tgoogle.golang.org/grpc@v1.49.0/server.go:936 +0x290\n","grpc.time_ms":"0.925","stacktrace":"github.com/grpc-ecosystem/go-grpc-middleware/v2/interceptors/logging.(*reporter).logMessage\n\tgithub.com/grpc-ecosystem/go-grpc-middleware/v2@v2.0.0-rc.2.0.20220505152843-58a406687f2d/interceptors/logging/interceptors.go:35\ngithub.com/grpc-ecosystem/go-grpc-middleware/v2/interceptors/logging.(*reporter).PostCall\n\tgithub.com/grpc-ecosystem/go-grpc-middleware/v2@v2.0.0-rc.2.0.20220505152843-58a406687f2d/interceptors/logging/interceptors.go:44\ngithub.com/grpc-ecosystem/go-grpc-middleware/v2/interceptors.UnaryServerInterceptor.func1\n\tgithub.com/grpc-ecosystem/go-grpc-middleware/v2@v2.0.0-rc.2.0.20220505152843-58a406687f2d/interceptors/server.go:25\ngoogle.golang.org/grpc.chainUnaryInterceptors.func1.1\n\tgoogle.golang.org/grpc@v1.49.0/server.go:1138\ngithub.com/grpc-ecosystem/go-grpc-middleware/v2/interceptors.UnaryServerInterceptor.func1\n\tgithub.com/grpc-ecosystem/go-grpc-middleware/v2@v2.0.0-rc.2.0.20220505152843-58a406687f2d/interceptors/server.go:22\ngoogle.golang.org/grpc.chainUnaryInterceptors.func1.1\n\tgoogle.golang.org/grpc@v1.49.0/server.go:1138\ngithub.com/grpc-ecosystem/go-grpc-middleware/v2/interceptors.UnaryServerInterceptor.func1\n\tgithub.com/grpc-ecosystem/go-grpc-middleware/v2@v2.0.0-rc.2.0.20220505152843-58a406687f2d/interceptors/server.go:22\ngoogle.golang.org/grpc.chainUnaryInterceptors.func1.1\n\tgoogle.golang.org/grpc@v1.49.0/server.go:1138\ngoogle.golang.org/grpc.chainUnaryInterceptors.func1\n\tgoogle.golang.org/grpc@v1.49.0/server.go:1140\ngithub.com/rilldata/rill/runtime/api._RuntimeService_ListCatalogObjects_Handler\n\tgithub.com/rilldata/rill/runtime/api/runtime_grpc.pb.go:758\ngoogle.golang.org/grpc.(*Server).processUnaryRPC\n\tgoogle.golang.org/grpc@v1.49.0/server.go:1301\ngoogle.golang.org/grpc.(*Server).handleStream\n\tgoogle.golang.org/grpc@v1.49.0/server.go:1642\ngoogle.golang.org/grpc.(*Server).serveStreams.func1.2\n\tgoogle.golang.org/grpc@v1.49.0/server.go:938"}
UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "AxiosError: Request failed with status code 500".

[ERROR] 14:28:18 UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "AxiosError: Request failed with status code 500".

```

To fix this, had to delete the `.db` files and re-import the sources

**Comment by begelundmuller** [comment]
I finally managed to reproduce this problem. It turned out to be a bug in DuckDB's ability to replay migrations that had only been saved in the WAL, but not merged into the `.db` file.

To reproduce:
1. Migrate up to DuckDB migration `0002.sql`
2. Add some data to `rill.catalog`
3. Migrate up to DuckDB migration `0003.sql` and immediately terminate (before DuckDB decides to merge the WAL into the `.db`)
4. Next time you restart, the error is reproduced

For now, https://github.com/rilldata/rill-developer/pull/1225 fixes this by forcing DuckDB to merge the WAL into the `.db` file after every migration.

We should file a bug report with DuckDB.
