### ISSUE TITLE
Rill start hangs

### ISSUE THREAD

**Issue by marcelteraflow** [rilldata/rill-developer#1439]
**Describe the bug**
Invoking `rill start` outputs the following and hangs forever:

```console
TypeError: Cannot read properties of undefined (reading 'setSocketServer')
    at new ExpressServer (/snapshot/v0.15.0-rill-developer/web-local/dist/web-local/src/server/ExpressServer.js:35:29)
    at StartCommand.sendActions (/snapshot/v0.15.0-rill-developer/web-local/dist/web-local/src/cli/StartCommand.js:26:15)
    at StartCommand.run (/snapshot/v0.15.0-rill-developer/web-local/dist/web-local/src/cli/DataModelerCliCommand.js:73:20)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at process.runNextTicks [as _tickCallback] (node:internal/process/task_queues:65:3)
    at Function.runMain (pkg/prelude/bootstrap.js:1984:13)
    at node:internal/main/run_main_module:17:47
```

 - OS: Macos Ventura 13.0.1
 - Browser Brave
 - Version 0.15.0

**Comment by AdityaHegde** [comment]
Hi @marcelteraflow  . This is a very generic error when our backend fails to come up. One big reason is when the port 8080 is already in use. We are changing quite a lot around this in our next release. Please update to it and let us know if you still face any issue.

**Comment by marcelteraflow** [comment]
Works perfectly now. Thank you!
