### ISSUE TITLE
Adding a leaderboard filter on a dimension value containing an apostrophe causes an error (improperly escaped strings in queries)

### ISSUE THREAD

**Issue by bcolloran** [rilldata/rill-developer#998]
**Describe the bug**

I have a dataset containing strings with apostrophes -- e.g addresses like `59 rue de l'Abbaye` or customer names like `Anna's Decorations, Ltd`. When I filter on these in a leaderboard, it blows up all the other leadearboards --

![image](https://user-images.githubusercontent.com/2380975/194431195-a5fc31d1-3157-4b20-9a07-9f8519950d6d.png)

It looks like the string is not escaped in the query, here is the error:

```
Error: Parser Error: syntax error at or near "Abbaye"
LINE 23: ...ies column that has the intended range
        WITH template as (
          SELECT 
            generate_series as ts 
          FROM 
            generate_series(
              date_trunc(
                'month', 
                TIMESTAMP '2003-01-06T00:00:00.000Z'
              ), 
              date_trunc(
                'month', 
                TIMESTAMP '2005-05-31T00:00:00.000Z'
              ),
              interval 1 month)
        ),
        -- transform the original data, and optionally sample it.
        series AS (
          SELECT 
            date_trunc('month', "date") as ts,
            count(*) as measure_0, sum(sales) as measure_1, sum(QUANTITYORDERED) as measure_2, sum(msrp) -sum(priceeach) as measure_3, sum(QUANTITYORDERED)/count(*) as measure_4, sum(QUANTITYORDERED) as measure_5
          FROM "Untitled_spreadsheet___sales_data_sample_model"  WHERE ("ADDRESSLINE1" = '59 rue de l'Abbaye')
                                                   ^
    at DuckDBClient.request (/home/brendan/rill/rill-developer/web-local/src/common/database-service/DuckDBClient.ts:162:13)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at DuckDBClient.execute (/home/brendan/rill/rill-developer/web-local/src/common/database-service/DuckDBClient.ts:55:20)
    at DatabaseTimeSeriesActions.generateTimeSeries (/home/brendan/rill/rill-developer/web-local/src/common/database-service/DatabaseTimeSeriesActions.ts:154:7)
    at DatabaseService.dispatch (/home/brendan/rill/rill-developer/web-local/src/common/database-service/DatabaseService.ts:78:12)
    at ActionQueueOrchestrator.run (/home/brendan/rill/rill-developer/web-local/src/common/priority-action-queue/ActionQueueOrchestrator.ts:30:24)
Error: Parser Error: syntax error at or near "Abbaye"
LINE 3: ...   SELECT count(*) as measure_0, "PRODUCTLINE" from "Untitled_spreadsheet___sa...
                                                  ^
    at DuckDBClient.request (/home/brendan/rill/rill-developer/web-local/src/common/database-service/DuckDBClient.ts:162:13)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at DuckDBClient.execute (/home/brendan/rill/rill-developer/web-local/src/common/database-service/DuckDBClient.ts:55:20)
    at DatabaseService.dispatch (/home/brendan/rill/rill-developer/web-local/src/common/database-service/DatabaseService.ts:78:12)
    at ActionQueueOrchestrator.run (/home/brendan/rill/rill-developer/web-local/src/common/priority-action-queue/ActionQueueOrchestrator.ts:30:24)
Error: Parser Error: syntax error at or near "Abbaye"
LINE 3: ...   SELECT count(*) as measure_0, "STATUS" from "Untitled_spreadsheet___sales_d...
              
...

```

(... and so on -- I included two copies of the error output block from `at DuckDBClient.request ` to `LINE 3: ... `, but that block is repeated for every dimension)

**Comment by AdityaHegde** [comment]
This was fixed and released in 0.12.x
